version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "studia-cicd-stack"
s3_prefix = "studia-cicd"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true